import React from 'react'
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid';

export const Learn = () => {
  return (
    <Box sx={{flexGrow:1}}>
      <Grid container spacing={2}>
        <Grid item xs={8}>
          <h1>Learn</h1>
          <h2>Total Bet:</h2>
          <p>
          This bet is for the amount of goals scored in the game (regulation only: meaning goals scored in extra time or penalties wouldn’t count). You have two options: over or under. Example: the total for the World Cup final was 2.5 goals. If you want to bet it’ll be a high scoring game take the over. To win your bet, at least 3 goals need to be scored. Since 3 > 2.5 goals. However, if you want to bet it’ll be a low scoring game, take the under. To win the bet, at most 2 goals can be scored since 2 < 2.5 goals. What if the line for the total changed from 2.5 goals to 3 goals? This means your bet can be over or under 3 goals. If exactly 3 goals are scored, then you either win or lose. You’d get your money back. This is called a push. 
          </p>

          
          <h3>Spread:</h3>
          <p>
          This bet is for backing the performance of a favorite or underdog in the game (regulation only: meaning goals scored in extra time or penalties wouldn’t count). You have two options: take the points for the  - (favorite) or + (underdog). Example: the spread for Argentina vs Panama is 2.5 goals. The favorite in this game is Argentina and the underdog is Panama. If you want to bet Argentina will win comfortably, take -2.5. To win your bet, Argentina’s margin of victory needs to be at least 3 goals. Since 3 > 2.5 goals. However, if you want to bet Panama won’t get blown out, take +2.5. To win the bet, Panama can’t lose by more than 2 goals.  Since 2 < 2.5 goals. What if the line for the spread changed from 2.5 goals to 3 goals? This means your bet can be for the favorite to win by more than 3 goals, or the underdog to lose by less than 3 goals. If Argentina’s margin of victory is exactly 3 goals, then you either win or lose. You’d get your money back. This is called a push. 
          </p>

          <h4>Moneyline:</h4>
          <p>
          This bet has three options: team A to win, team B to win, or neither team to win (tie). Essentially you bet who you think wins- remember in soccer this could be neither team (draw). As mentioned before, - means favorite and + means underdogs. This is also true when looking at the odds for moneyline. Example: the moneyline for the World Cup final (90 min regulation) was choice 1) Argentina  +160, choice 2) France +185, or choice 3) Draw +205. Out of the three choices, none is a favorite. All choices are underdogs because there is an implied probability around 33% for each choice. Your bet wins if you correctly pick the outcome in regulation (either Argentina win, France win, or neither wins: draw). An example of a choice being a favorite is: Argentina vs Panama choice 1) Argentina -600 choice 2) Panama +3000 choice 3) Draw +800. The implied probability of Argentina winning is around 85%. A draw is around 10%. And Panama winning is around 5%. If you bet Argentina to win, you’d need to risk $600 to win $100. If you bet the draw, a $100 bet would win you $800. If you bet Panama to win, a $100 bet would win you $3000. Let’s test your knowledge: the World Cup final (Argentina vs France) ended up being 2-2 in regulation. How much did $100 bettors win/lose for betting Argentina moneyline, France moneyline, & the draw? The answer is the following: lost $100, lost $100, won $205. 
          </p>

          <h5>Implied Probability:</h5>
          <p>
          Divide the amount you’re betting by the cash out of the bet. -110 would be 110/210 = 0.524. Meaning to break even, you need to be 52.4% accurate assuming all your bets are $110 at -110 odds. 
          </p>

          <h6>Sportsbooks Theory:</h6>
          <p>
          Have you ever made a bet with a friend? I bet you have. For me, it was a $20 bet for correctly picking the winner of Super Bowl 55. I risked $200, and since I won, I collected $200 from my friend. Essentially I doubled my money. What if I went to the sportsbooks instead? Let’s look at the lines: moneyline for the rams was -200 while the bengals were +160. Meaning if I risked the same $200, I would have only won $100. Why? Because the implied probability of the rams winning > the implied probability of the bengals winning, according to the sportsbooks. So I’d need to risk more money to win $200. I would need to bet $400 to win $200 (rams), while my friend would need to bet $125 to win $200 (bengals) and a $200 bet would win $320. Let’s look at another line: the spread which was -3.5 for the Rams & +3.5 for the bengals. How much would I get for betting $100 on the spread? I would win $90.90. To win $100 I’d need to risk $110. Why wouldn’t I win $100 from a $100 bet, since the implied probability for the spread is 50% (meaning 50% probability the rams win by more than 3 and 50% they don’t). Because this is the price for making bets with sportsbooks: you need to bet $110 to win $100 from 50% implied probability. This is called the vig. Sportsbooks make money off the vig. The objective of the sportsbook when posting lines of -110 (this is your generic line for spreads & totals. Meaning there is a 50% implied probability on both sides of the bet) is for there to be even money on both sides. So no matter the outcome of the game, the sportsbook makes money off the vig.  The bookies clearly have the edge, in this case a 4.8% house edge for each dollar wagered. Why do lines change? Like the spread of the Super Bowl went from 4.5 to 3.5. Because there wasn’t even money on both sides of the initial spread. More money was on the bengals. Therefore, the sportsbook adjusted the spread to 4.0 points, in hopes of incentivizing people to bet on -4 so more money goes on the rams. Guess what, the incentive wasn’t enough, so the line dropped to -3.5 & stayed here. The sportsbook had even money on both sides of the spread, so no matter the outcome, the casino made money from their millions of clients via the vig. What if there isn’t even money on both sides of the spread? The sportsbook lives with the results. They win more often than not since the public (your casual bettor) loses money. 3-5% of people make money, these are usually your professional bettors aka sharps. Why? Casual bettors bet for entertainment & don’t have a plan for managing their money. Such as only placing 5-leg parlays.
          </p>

          <h7>Avoid Parlays:</h7>
          <p>
          Parlays are a single bet contingent on all legs hitting. A leg is a selection on a game. An Example of a 2-leg parlay is betting the total for the World Cup and the spread. Here, the bet needs zero losses or you lose the bet. The payout increases with the selections you add, but the implied probability decreases. A 2-leg parlay with both selections at -110 odds, for a $110 bet, has a payout of $396. Essentially, you are betting $110 on the first leg, and if it hits, you’d have $210. Then you are betting the $210 on the last leg, and if it hits, you’d have $396. If any selection loses, your bet loses. If any selection has a push, that selection is voided (not selections: the payout for the bet just wouldn’t be as high since there’s one less leg). Professional bettors don’t depend on parlays for making money, since the implied probability significantly lowers. Instead, professionals rely on straight bets at near -110 odds. Because winning at least 52.4% of their bets is a more reliable method for long term success. If you only placed -300 bets, you’d need to win at least 75% the time to not lose money. If you lose twice in a row at -300 odds (to win $100), you’re instantly down $600. Meanwhile at -110 odd (to win $100). You’d need to lose six times in a row to lose $660. What if I like one selection way more than my other selection? Casuals would make this a 2-leg parlay, based on the implied probability (at -110 odds) they have approximately a 25% of winning. The alternative is placing two individual bets. If both win, you win $100 per selection. If one loses and one wins, you lose $10. If both loses, you lose $220. And if there’s a push, you get $110 back per the selection. What do pros do? Pros place individual bets, but they give selections “units” based on how much they love a pick.
          </p>

          <h8>Money Management:</h8>
          <p>
          Doc Sports' Handicappers implement the following unit system: 1 unit (generic bet) is $110 with a max of 8 units (this would be reserved for your premium picks, “game of the year”) is $880. Because of their bankroll, they usually don’t make generic bets. They go up from there if the pick is their “game of the day (3 or 4 units)”, “game of the week (5 units)” ,“game of the month (6 units)” ,“game of the season (7 units)”, “game of the year (8 units). Also because of their bankroll, they can place multiple unit picks per day per sport. The more aggressive you are, the more frequency you place 6, 7, and 8 unit picks. Professionals usually tier their units in the following manner: 8 unit picks when they absolutely love a pick (frequency: once a month), 7 unit bets when they love a pick (multiple per week), 3 or 4 unit picks when they like a pick (usually at least once a day), and 6 or 5 units when they’re in the middle of loving and liking a pick (usually at least once a day). Every unit you’re up to is $100. So if in a season you go up 100 units, you made $10,000. Professionals usually make this much per season, following the unit system. The unit system is a proven method of managing your bankroll for Doc Sports' Handicappers. Also, your single unit should be near 1% of your bankroll ($110 per unit professional bettors bet around 1% of their $10,000 bankroll per season). Why? To gamble responsibly. If your unit is 10% of your bankroll, to get to $0 you’d only need to go down -10 units. Let’s say you instantly miss a 7 and a 3 unit pick; you’re at -10 units. The 1% of your bankroll method protects you from losing significant money fast (bankroll) when you’re on a cold streak and protects you from variance and outliers. Remember nothing is 100% or a lock. If you risk significant money & you lose, it may be from insane moments like Messi tearing his ACL or missing all his penalties, now you have to work hard to make those units back. If you go on a cold streak, you’ve lost so much money fast. Even more if you lost discipline and increased your bets in hopes of chasing the money back.If you're on a hot streak, stay humble. Regression is always a possibility. Don’t gamble that luck is on your side, instead invest via a strategic strategy with money management (proper unit system) and your sports expertise. 
          </p>

          <h9>Your Sports Expertise:</h9>
          <p>
          Have you noticed all the numbers in here? Sports betting has so many stats and lines. Pros take advantage of weak lines made by computer models and algorithms. Like a pick at -110 odds has a 52.4% implied probability, but you like the pick so much you think it’s 60% implied probability. You see you have value at a 7.4% edge so you place a 3 unit bet. How do you predict sports, so that you can identify a total or spread at 60% implied probability? This comes down to your experience, research, & analysis expertise. What is this? Experience is when you learn from past mistakes and have a strong familiarity of how the system works. Research is when you find quality stats & information to analyze. Analysis dictates how successful you are: it’s your right and wrong ratio with picks, units. To be successful, you can incorporate many tools. The most valuable are experience and research, as previously discussed. You lean on these tools when you have tons of detailed stats, with high sample sizes (up to your discretion). You then balance, implement, and analyze variables like regression, lineups plus more to find your implied probability. You’d do the same if you don’t have quality stats, but quality stats gives you a mathematical perspective of history; another perspective. Find out what matters for you- what are your subconscious and subconscious algorithms, models, perspectives? Do you determine one team is more motivated than the other, how? Unique to you. Remember, stats matter because history tends to repeat itself. Like if the better defensive team won every Super Bowl, for 58 years now, chances are the winner for the next Super Bowl is the better defensive team. That begs the question: how do you know one is the better defensive team? Can you think of other tools and other variables to leverage? To find the implied probability that one team will perform better and likely win the game? Can you find the relevance of different stats?
          </p>
       
        </Grid>
      </Grid>
    </Box>
  )
}
